# Generated by Django 2.2.4 on 2019-08-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount_base', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
